locationtech/rasterframes

- deployment/docker/jupyter/Getting Started with RasterFrames (scala).ipynb
- deployment/docker/jupyter/Getting Started with RasterFrames.ipynb
Notebook fixes and other enhancements in #12
> WIP: Notebook enhancements  

- core/src/main/scala/astraea/spark/rasterframes/RasterFunctions.scala
- core/src/main/scala/astraea/spark/rasterframes/functions/package.scala
- core/src/main/scala/astraea/spark/rasterframes/jts/ReprojectionTransformer.scala
- core/src/main/scala/astraea/spark/rasterframes/util/package.scala
- core/src/test/scala/astraea/spark/rasterframes/JTSSpec.scala
- core/src/test/scala/astraea/spark/rasterframes/TestEnvironment.scala
- pyrasterframes/python/README.rst
- pyrasterframes/python/pyrasterframes/rasterfunctions.py
- pyrasterframes/python/pyrasterframes/types.py
- pyrasterframes/python/tests/PyRasterFramesTests.py
- pyrasterframes/src/main/scala/astraea/spark/rasterframes/py/PyRFContext.scala
> Reprojection for Geometry Columns

- core/src/main/scala/astraea/spark/rasterframes/functions/package.scala
> Fix polarity error in SQL rf_noDataCells

- core/src/main/scala/astraea/spark/rasterframes/RasterFunctions.scala
- core/src/main/scala/astraea/spark/rasterframes/functions/package.scala
- docs/src/main/tut/release-notes.md
- pyrasterframes/python/pyrasterframes/rasterfunctions.py
Please take a look for possible copy-paste errors...
> Add <, <=, >, >=, ==, != functions.

- pyrasterframes/src/main/scala/astraea/spark/rasterframes/py/PyRFContext.scala
This PR adds new `asRF` methods, `toSpatialMultibandTileLayerRDD`, and `toSpaceTimeMultibandTileLayerRDD` to `PyRFContext` in order to integrate `pyrasterframes` into GeoPySpark.
Note: This PR is based on another, open PR #54 which should be merged before this one.
> GeoPySpark Integration Methods

- deployment/README.md
Unsolicited PR here.
I've update the `deployment/README.md` to integrate some of my notes and things that I often do with the notebook server.
> Tweaks to deployment readme

- pyrasterframes/python/pyrasterframes/rasterfunctions.py
- pyrasterframes/python/tests/PyRasterFramesTests.py
> Add maskByValue to Python API

- core/src/main/scala/astraea/spark/rasterframes/functions/package.scala
> normalized difference converts inputs to float

- core/src/test/scala/astraea/spark/rasterframes/ref/LayerSpaceSpec.scala
Signed-off-by: Matthew Eldridge <meldridge@astraea.io>
> Fixed test to handle adjusted extents via ReprojectRasterExtent

- core/src/main/scala/astraea/spark/rasterframes/util/package.scala
> Allow lower case EPSG and CRS WKT in reproject_geometry #92

- docs/src/main/tut/pyrasterframes.md
- docs/src/main/tut/reference.md
> Add function references for SQL and Python API's.

- docs/src/main/tut/reference.md
> Refactor docs cellTypes to cell_types

- README.md
This simple pull request add a section containing build instruction.
> Add build instruction to the README.

- docs/src/main/tut/release-notes.md
> Update release notes for recently merged work

- .circleci/config.yml
- core/src/it/scala/org/locationtech/rasterframes/ref/RasterSourceIT.scala
Signed-off-by: Phil Varner <pvarner@astrea.io>
> fix circleci paths and fix ITs broken by mis-merge

- core/src/main/scala/org/locationtech/rasterframes/ref/RasterSource.scala
> Experiment with read retries to handle BufferUnderflowExceptions.

- pyrasterframes/src/main/python/examples/__init__.py
- pyrasterframes/src/main/python/pyrasterframes/rf_types.py
- pyrasterframes/src/main/python/setup.py
> WIP: Fix python unit tests

- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/RasterSourceToRasterRefs.scala
- datasource/src/test/scala/org/locationtech/rasterframes/datasource/rastersource/RasterSourceDataSourceSpec.scala
> RasterSource column duplication bug fix.

- datasource/src/main/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceDataSource.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceRelation.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/raster/package.scala
- datasource/src/test/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceDataSourceSpec.scala
- pyrasterframes/src/main/python/docs/raster-io.pymd
Also: Normalized handling of CSV tables into DataFrame input path.
Closes #168
> Added joining of extra columns from catalog into RasterFrame.

- bench/src/main/scala/org/locationtech/rasterframes/bench/RasterRefBench.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/generators/RasterSourceToRasterRefs.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/generators/RasterSourceToTiles.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/URIToRasterSource.scala
- core/src/test/scala/org/locationtech/rasterframes/ref/RasterRefSpec.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceDataSource.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceRelation.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/raster/package.scala
- datasource/src/test/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceDataSourceSpec.scala
- pyrasterframes/src/main/python/docs/raster-io.pymd
- pyrasterframes/src/main/python/pyrasterframes/__init__.py
- pyrasterframes/src/main/python/tests/PyRasterFramesTests.py
> Implemented switch to RasterSourceRelation to control lazy or strict reading of tiles.

- .circleci/config.yml
- pyrasterframes/src/main/python/docs/raster-io.pymd
- pyrasterframes/src/main/python/setup.py
Now has job for building docs.
> CircleCI tweaks and fixes.

- pyrasterframes/src/main/python/pyrasterframes/rasterfunctions.py
- pyrasterframes/src/main/python/pyrasterframes/utils.py
to improve readability and discoverability.
> Converted generic varargs to named args for various Python rf_ functions

- project/PythonBuildPlugin.scala
- pyrasterframes/src/main/python/docs/raster-catalogs.pymd
- pyrasterframes/src/main/python/docs/raster-io.md
- pyrasterframes/src/main/python/docs/raster-read.pymd
- pyrasterframes/src/main/python/docs/raster-write.pymd
- pyrasterframes/src/main/python/pyrasterframes/utils.py
- rf-notebook/src/main/docker/Dockerfile
Refining structure. Added "Catalogs" section.
> Updates to Raster IO Docs

- experimental/src/it/scala/org/locationtech/rasterframes/experimental/datasource/awspds/L8CatalogRelationTest.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/PDSFields.scala
> L8 catalog use Extent schema not envelope

- pyrasterframes/src/main/python/docs/reference.pymd
Signed-off-by: Courtney Whalen <cwhalen@astraea.io>
> convert function ref code chunks to running code

- pyrasterframes/src/main/python/pyrasterframes/__init__.py
- pyrasterframes/src/main/python/tests/PyRasterFramesTests.py
> Raster reader can take a Pandas DataFrame or geopandas GeoDF

- pyrasterframes/src/main/python/docs/nodata-handling.pymd
> Small docs tweaks lingering from PR 187

- pyrasterframes/src/main/python/docs/local-algebra.pymd
Added a picture for clarity, and fixed a pweave related display issue.
> Update Local Algebra Documentation

- pyrasterframes/src/main/python/pyrasterframes/rf_ipython.py
> Remove stray paren from Tile PNG header

- docs/src/main/paradox/release-notes.md
> Update release notes to reflect change at e8d117c75c4d

- core/src/main/scala/org/locationtech/rasterframes/expressions/aggregates/LocalMeanAggregate.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/localops/BiasedAdd.scala
- pyrasterframes/src/main/python/docs/reference.pymd
- pyrasterframes/src/main/python/setup.py
- pyrasterframes/src/main/python/tests/GeoTiffWriterTests.py
- pyrasterframes/src/main/python/tests/PyRasterFramesTests.py
- pyrasterframes/src/main/python/tests/RasterFunctionsTests.py
Created new BiasedAdd for Aggregate use.
Addresses: https://github.com/locationtech/rasterframes/issues/229
Related: #225 #230
> Fixed `Add` expression to use GT behavior

- pyrasterframes/src/main/python/docs/concepts.md
- pyrasterframes/src/main/python/docs/raster-catalogs.pymd
- pyrasterframes/src/main/python/docs/raster-read.pymd
@courtney-whalen can you take a look. Referencing #248 items,
* haven't explicitly addressed the experimental descriptor on the catalogs
* i did a show (head) on the earlier external catalog example. We'd rather not do it on the built in ones because they can be slow to initialize
> Add band to concepts, address issue 248 items on catalog doc page

- rf-notebook/src/main/docker/Dockerfile
Signed-off-by: Tom Schroeder <tschroeder@astraea.io>
> Update LD_LIBRARY_PATH to ensure access to GDAL in rasterframes notebook

- docs/src/main/paradox/release-notes.md
See also updated issue description
> Docs: known issue for 188 

- pyrasterframes/src/main/python/docs/raster-read.pymd
- pyrasterframes/src/main/python/docs/raster-write.pymd
- pyrasterframes/src/main/python/docs/reference.pymd
- pyrasterframes/src/main/python/pyrasterframes/__init__.py
> Docs fixes in raster read 

- core/src/main/scala/org/locationtech/rasterframes/model/FixedRasterExtent.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/RasterRef.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/RasterSource.scala
- core/src/test/scala/org/locationtech/rasterframes/ref/RasterRefSpec.scala
- core/src/test/scala/org/locationtech/rasterframes/ref/RasterSourceSpec.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala
- datasource/src/test/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSourceSpec.scala
- datasource/src/test/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceDataSourceSpec.scala
- project/RFDependenciesPlugin.scala
> Fixes #242.

- .circleci/config.yml
- docs/README.md
- pyrasterframes/src/main/python/docs/raster-catalogs.pymd
- pyrasterframes/src/main/python/setup.py
Pretty light changes, trying to get a handle on docs build stability and also docs on docs.
> Docs build and ci improvements

- pyrasterframes/src/main/python/pyrasterframes/version.py
> Bump python development version to match JVM version

- core/src/it/scala/org/locationtech/rasterframes/ref/RasterRefIT.scala
- core/src/main/scala/org/locationtech/rasterframes/encoders/StandardSerializers.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/DynamicExtractors.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/accessors/RealizeTile.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/aggregates/TileRasterizerAggregate.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/RGBComposite.scala
- core/src/main/scala/org/locationtech/rasterframes/extensions/DataFrameMethods.scala
- core/src/main/scala/org/locationtech/rasterframes/util/package.scala
- core/src/test/scala/org/locationtech/rasterframes/RasterFunctionsSpec.scala
- core/src/test/scala/org/locationtech/rasterframes/TestData.scala
- core/src/test/scala/org/locationtech/rasterframes/encoders/CatalystSerializerSpec.scala
- core/src/test/scala/org/locationtech/rasterframes/ref/RasterRefSpec.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala
- datasource/src/test/scala/org/locationtech/rasterframes/datasource/geotrellis/GeoTrellisDataSourceSpec.scala
- experimental/src/it/scala/org/locationtech/rasterframes/experimental/datasource/awspds/L8CatalogRelationTest.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/CachedDatasetRelation.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/ResourceCacheSupport.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/L8CatalogDataSource.scala
Starting to take steps toward making it easier to create RGB color composites. Also fixes bug in L8 catalog relation.
> Incremental step toward easier aggregate raster generation.

- core/src/test/scala/org/locationtech/rasterframes/RasterFunctionsSpec.scala
> Add failing unit test for issue 333, error in rf_agg_local_mean

- core/src/main/scala/org/locationtech/rasterframes/ref/RasterRef.scala
- core/src/test/scala/org/locationtech/rasterframes/TestEnvironment.scala
- docs/src/main/paradox/release-notes.md
> Fixes Parquet serialization issue with `RasterRef`s 

- rf-notebook/src/main/docker/Dockerfile
> Bumped Spark version to 2.3.4

- core/src/test/scala/org/locationtech/rasterframes/TestData.scala
- pyrasterframes/src/main/python/docs/concepts.md
- pyrasterframes/src/main/python/docs/getting-started.pymd
- pyrasterframes/src/main/python/docs/reference.pymd
> Doc fixes missing @ref: prefixes.

- core/src/main/resources/reference.conf
- core/src/main/scala/org/locationtech/rasterframes/expressions/accessors/GetCRS.scala
- core/src/main/scala/org/locationtech/rasterframes/model/LazyCRS.scala
- core/src/test/scala/org/locationtech/rasterframes/RasterFunctionsSpec.scala
- core/src/test/scala/org/locationtech/rasterframes/TestEnvironment.scala
- docs/src/main/paradox/release-notes.md
- pyrasterframes/src/main/python/docs/reference.pymd
> Added abiltiy to pass a crs specification string to `rf_crs`.

- build/circleci/Dockerfile
- build/circleci/Makefile
- build/circleci/README.md
Signed-off-by: Phil Varner <pvarner@astraea.io>
> update python in docker image

- core/src/main/scala/org/apache/spark/sql/rf/TileUDT.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/DelegatingRasterSource.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/GDALRasterSource.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/RasterRef.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/RasterSource.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/SimpleRasterInfo.scala
- core/src/main/scala/org/locationtech/rasterframes/tiles/ProjectedRasterTile.scala
- core/src/test/scala/org/locationtech/rasterframes/RasterFrameSpec.scala
- core/src/test/scala/org/locationtech/rasterframes/ref/RasterRefSpec.scala
- project/plugins.sbt
- pyrasterframes/src/main/python/pyrasterframes/rf_context.py
- pyrasterframes/src/main/python/pyrasterframes/rf_types.py
- pyrasterframes/src/main/scala/org/locationtech/rasterframes/py/PyRFContext.scala
> Fixed eager loading of RasterRef fields.

- core/src/main/scala/org/locationtech/rasterframes/expressions/BinaryLocalRasterOp.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/BinaryRasterOp.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/UnaryLocalRasterOp.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/generators/RasterSourceToTiles.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/Mask.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/RasterRefToTile.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/SetNoDataValue.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/URIToRasterSource.scala
- core/src/main/scala/org/locationtech/rasterframes/extensions/RasterFrameLayerMethods.scala
- core/src/main/scala/org/locationtech/rasterframes/rasterframes.scala
- core/src/main/scala/org/locationtech/rasterframes/ref/RangeReaderRasterSource.scala
- core/src/main/scala/org/locationtech/rasterframes/util/package.scala
- core/src/test/scala/org/locationtech/rasterframes/TestEnvironment.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffRelation.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotrellis/GeoTrellisRelation.scala
- docs/src/main/paradox/release-notes.md
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/CachedDatasetRelation.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/DownloadSupport.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/ResourceCacheSupport.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/L8CatalogDataSource.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/L8CatalogRelation.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/MODISCatalogDataSource.scala
- experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/MODISCatalogRelation.scala
- project/RFAssemblyPlugin.scala
- project/RFDependenciesPlugin.scala
> Reworking of logging usage to fix #293

- rf-notebook/build.sbt
- rf-notebook/src/main/docker/Dockerfile
Signed-off-by: Phil Varner <pvarner@astraea.io>
> merge pyspark-notebook:spark-2.3.4-hadoop-2.7 Dockerfile into this one

- rf-notebook/src/main/docker/Dockerfile
This has already been hotfix applied to 0.8.4 (only the Docker image needed updating).
> Attempt to fix "ImportError: libpoppler.so.76" 

- core/src/main/scala/org/locationtech/rasterframes/extensions/RasterJoin.scala
- core/src/test/scala/org/locationtech/rasterframes/RasterJoinSpec.scala
> Added the ability to do a raster_join on proj_raster types.

- pyrasterframes/src/main/python/pyrasterframes/rf_types.py
- pyrasterframes/src/main/python/tests/ExploderTests.py
- pyrasterframes/src/main/python/tests/NoDataFilterTests.py
We did not previously have the correct mixins for correctly saving and loading the Transformers on the python side. Add unit tests and fixes.
Fix #425
> Fix #425 ML Pipeline save/load

- pyrasterframes/src/main/python/pyrasterframes/rasterfunctions.py
- pyrasterframes/src/main/python/tests/RasterFunctionsTests.py
> Fix rf_local_extract_bits argument parsing

- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/Mask.scala
- core/src/test/scala/org/locationtech/rasterframes/MaskingFunctionsSpec.scala
- core/src/test/scala/org/locationtech/rasterframes/RasterFunctionsSpec.scala
- core/src/test/scala/org/locationtech/rasterframes/functions/MaskingFunctionsSpec.scala
- docs/src/main/paradox/release-notes.md
- pyrasterframes/src/main/python/docs/masking.pymd
> Fix for 409: assert on mask target must have NoData defined

- docs/src/main/paradox/raster-processing.md
- pyrasterframes/src/main/python/docs/raster-join.pymd
- pyrasterframes/src/main/python/docs/raster-read.pymd
> Add raster join page to docs; expand spatial index discussion

- pyrasterframes/src/main/python/docs/unsupervised-learning.pymd
> Unsupervised learning column selection

- core/src/main/scala/org/locationtech/rasterframes/expressions/DynamicExtractors.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/ExtentToGeometry.scala
- core/src/main/scala/org/locationtech/rasterframes/model/LongExtent.scala
- pyrasterframes/src/main/python/pyrasterframes/rasterfunctions.py
- pyrasterframes/src/main/python/tests/RasterFunctionsTests.py
> st_geometry extents bug

- core/src/main/scala/org/locationtech/rasterframes/encoders/StandardSerializers.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/DynamicExtractors.scala
- core/src/main/scala/org/locationtech/rasterframes/expressions/accessors/GetCRS.scala
- core/src/main/scala/org/locationtech/rasterframes/extensions/RasterJoin.scala
- core/src/main/scala/org/locationtech/rasterframes/functions/package.scala
- core/src/test/scala/org/locationtech/rasterframes/expressions/DynamicExtractorsSpec.scala
- pyrasterframes/src/main/python/pyrasterframes/__init__.py
- pyrasterframes/src/main/python/pyrasterframes/rf_types.py
- pyrasterframes/src/main/python/tests/PyRasterFramesTests.py
Closes #462 
cc: @vpipkt @courtney-whalen
> Fix for NPE in reproject_and_merge UDF

- build.sbt
Signed-off-by: Jean-Denis Giguère <jean-denis@anagraph.io>
> Fix #467: missing geotrellis-s3-spark dependency

- pyrasterframes/src/main/python/tests/IpythonTests.py
See #458 in particular this discussion: https://github.com/locationtech/rasterframes/issues/458#issuecomment-584739934
> IPython null value in Tile column throws

- core/src/main/scala/org/locationtech/rasterframes/extensions/DataFrameMethods.scala
- core/src/main/scala/org/locationtech/rasterframes/extensions/RasterJoin.scala
- core/src/main/scala/org/locationtech/rasterframes/extensions/ReprojectToLayer.scala
- core/src/test/scala/org/locationtech/rasterframes/RasterLayerSpec.scala
- datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotrellis/GeoTrellisRelation.scala
- pyrasterframes/src/main/python/pyrasterframes/__init__.py
- pyrasterframes/src/main/scala/org/locationtech/rasterframes/py/PyRFContext.scala
> Fix for pyspark AttributeError on sparksession _conf member

- .circleci/config.yml
- project/build.properties
- pyrasterframes/src/main/python/requirements.txt
- pyrasterframes/src/main/python/setup.py
- pyrasterframes/src/main/python/tests/GeotrellisTests.py
> Pin jupyter-client version for comatibility with pweave

- .circleci/config.yml
In local circleci command, I was able to get past the current job failure. Waiting for circle build to see if that's all we need.
> Fix failing doc build on Circle CI

- pyrasterframes/src/main/python/docs/raster-join.pymd
didn't correctly update this from PR #495
> Fix raster join docs

- core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/RenderPNG.scala
- core/src/main/scala/org/locationtech/rasterframes/util/package.scala
- core/src/test/scala/org/locationtech/rasterframes/functions/TileFunctionsSpec.scala
- datasource/src/test/scala/examples/NAIPMultibandRead.scala
- docs/src/main/paradox/release-notes.md
- pyrasterframes/src/main/python/docs/aggregation.pymd
- pyrasterframes/src/main/python/docs/description.pymd
- pyrasterframes/src/main/python/docs/ipython.pymd
- pyrasterframes/src/main/python/docs/languages.pymd
- pyrasterframes/src/main/python/docs/local-algebra.pymd
- pyrasterframes/src/main/python/docs/masking.pymd
- pyrasterframes/src/main/python/docs/nodata-handling.pymd
- pyrasterframes/src/main/python/docs/numpy-pandas.pymd
- pyrasterframes/src/main/python/docs/raster-catalogs.pymd
- pyrasterframes/src/main/python/docs/raster-join.pymd
- pyrasterframes/src/main/python/docs/raster-read.pymd
- pyrasterframes/src/main/python/docs/raster-write.pymd
- pyrasterframes/src/main/python/docs/supervised-learning.pymd
- pyrasterframes/src/main/python/docs/time-series.pymd
- pyrasterframes/src/main/python/docs/unsupervised-learning.pymd
- pyrasterframes/src/main/python/docs/vector-data.pymd
- pyrasterframes/src/main/python/docs/zonal-algebra.pymd
> Added rendering special case to integral tiles with sparse histograms.
