locationtech/rasterframes

core/src/main/scala/astraea/spark/rasterframes/RasterFunctions.scala, core/src/main/scala/astraea/spark/rasterframes/functions/package.scala, core/src/test/scala/astraea/spark/rasterframes/GTSQLSpec.scala, pyrasterframes/python/pyrasterframes/rasterfunctions.py
Function to mask tile `T1` where tile `T2` equals `v`
Use cases would be cloud or snow masks from data producers. 
=> Add maskByValue function to scala, sql, and py apis.

core/src/main/scala/astraea/spark/rasterframes/ml/NoDataFilter.scala, pyrasterframes/python/pyrasterframes/rasterfunctions.py, pyrasterframes/src/main/scala/astraea/spark/rasterframes/py/PyRFContext.scala
Add aliases for scalar arithmetic, separating double and int implementations to deal with the scala numeric. Fix the way NoDataFilter converts from an arrayList to an array.
=> Fix scalar arithmetic and noDataFilter array conversion

pyrasterframes/python/pyrasterframes/rasterfunctions.py
=> Add rf_render_matrix back to pyrasterframes.rasterfunctions

pyrasterframes/python/pyrasterframes/__init__.py, pyrasterframes/python/pyrasterframes/rf_types.py, pyrasterframes/python/tests/PyRasterFramesTests.py
If a Python `rf_types.Tile` built in arithmetic function results in numpy converting the underlying dtype we will honor that in the returned Tile's `cell_type`. Also makes already merged unit test `test_udf_np_implicit_type_conversion` pass.
=> Built in Tile __add__ etc follows numpy dtype conversions

core/src/it/scala/org/locationtech/rasterframes/ref/RasterSourceIT.scala, project/RFDependenciesPlugin.scala
Currently core dumps on MacOS.
=> Upgraded gdal-warp-bindings

core/src/main/scala/org/locationtech/rasterframes/ref/RasterSource.scala, core/src/test/scala/org/locationtech/rasterframes/ref/RasterSourceSpec.scala, pyrasterframes/src/main/python/docs/raster-write.pymd, pyrasterframes/src/main/python/tests/GeoTiffWriterTests.py, pyrasterframes/src/main/python/tests/PyRasterFramesTests.py
Fix for #169  
The java.net.URI is a java object so possibly the URL.scheme can come back as `null` which was not always handled.
In the most important case in `RasterSource.IsDefaultGeoTiff.unapply` we made the faulty assumption that an empty scheme on a java.net.URI is the empty string `""` but never check for `null`.
Fixes the null check in that case.
This requires either no gdal support or config `rasterframes.prefer-gdal=false` to trigger it. Which is why it passed on circle but failed on travis.
=> Use implicit file:// for schemeless paths with leading /

docs/README.md, project/PythonBuildPlugin.scala, pyrasterframes/README.md
=> Clarify pyrasterframes/package sbt log statement re Maven python source artifact 

core/src/it/scala/org/locationtech/rasterframes/ref/RasterSourceIT.scala, pyrasterframes/src/main/python/docs/nodata-handling.pymd, pyrasterframes/src/main/python/docs/reference.pymd, pyrasterframes/src/main/python/docs/unsupervised-learning.pymd, pyrasterframes/src/main/python/pyrasterframes/rasterfunctions.py, pyrasterframes/src/main/python/pyrasterframes/rf_types.py, pyrasterframes/src/main/python/tests/PyRasterFramesTests.py, pyrasterframes/src/main/python/tests/RasterFunctionsTests.py
Note the more careful parsing of user defined nodata.
It's tagged 0.8.0 because it is a small fry but we can easily push it off.
=> Document and improve use of CellType in rasterfunctions args

pyrasterframes/src/main/python/pyrasterframes/rf_ipython.py
A few changes:
- Tile dimensions no longer affect ipython render size. 10x10 tile renders the same size as a 1000x1000
- Tile columns render such that the tiles are slightly smaller than if the tile was rendered by itself. 
- Font size of the title scales with the render size of the tile.
Signed-off-by: Eric Culbertson <eculbertson@astraea.io>
=> Tile render adjustments

.circleci/config.yml, pyrasterframes/src/main/python/docs/time-series.pymd, pyrasterframes/src/main/python/requirements.txt, pyrasterframes/src/main/python/setup.py
In the time-series documentation page:
* configure circle CI to save intermediate markdown files as artifacts on docs build failure
* simplify rest request to argis
* rest request specify `geojson` format
* attempt to embed folium
* generate folium.Map
* save it as html to temp location
* create an `<iframe>` within a markdown file to `@@include`
* read geojson with spark DataSource
* simplify geometry
* cross join catalog and vector data
* try to speed up execution?
Should fix #288 #283 #285 
Please squash merge!
=> Time series docs improvements 

core/src/main/scala/org/locationtech/rasterframes/expressions/generators/ExplodeTiles.scala, core/src/main/scala/org/locationtech/rasterframes/ml/TileColumnSupport.scala, core/src/test/scala/org/locationtech/rasterframes/ml/TileExploderSpec.scala, docs/src/main/paradox/release-notes.md, pyrasterframes/src/main/python/docs/vector-data.pymd, pyrasterframes/src/main/python/tests/ExploderTests.py
=> Updated ExplodeTiles to work with proj_raster type.

core/src/main/scala/org/locationtech/rasterframes/expressions/generators/RasterSourceToRasterRefs.scala, core/src/test/scala/org/locationtech/rasterframes/ref/RasterRefSpec.scala, docs/src/main/paradox/release-notes.md, pyrasterframes/src/main/python/tests/RasterSourceTest.py
=> Fixed Exception swallowing in RasterSource.

core/src/it/scala/org/locationtech/rasterframes/ref/RasterRefIT.scala, core/src/main/scala/org/locationtech/rasterframes/expressions/aggregates/ProjectedLayerMetadataAggregate.scala, core/src/main/scala/org/locationtech/rasterframes/expressions/aggregates/TileRasterizerAggregate.scala, core/src/main/scala/org/locationtech/rasterframes/expressions/generators/ExplodeTiles.scala, core/src/main/scala/org/locationtech/rasterframes/extensions/RFSpatialColumnMethods.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSource.scala, datasource/src/test/scala/org/locationtech/rasterframes/datasource/geotiff/GeoTiffDataSourceSpec.scala, docs/src/main/paradox/release-notes.md, experimental/src/it/scala/org/locationtech/rasterframes/experimental/datasource/awspds/L8CatalogRelationTest.scala
=> Fixed handling of aggregate extent and image size on geotiff write.

pyrasterframes/src/main/python/docs/vector-data.pymd, pyrasterframes/src/main/python/pyrasterframes/__init__.py, pyrasterframes/src/main/python/tests/RasterFunctionsTests.py
Just cause I was feeling paranoid about some other error I was encountering, I wrote this unit test. Also the import of geomesa_pyspark.types is an often enough encountered gotcha.
=> Add rf_mask unit test in python, import geomesa types with module import

.travis.yml, core/src/test/scala/org/locationtech/rasterframes/ref/RasterRefSpec.scala
Closes #393 by invalidation.
Depends on #391
=> Expanded RasterRefSpec to ensure lazy tiles provide metadata without I/O

datasource/src/main/scala/org/locationtech/rasterframes/datasource/raster/RasterSourceRelation.scala, experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/CachedDatasetRelation.scala, experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/L8CatalogRelation.scala, experimental/src/main/scala/org/locationtech/rasterframes/experimental/datasource/awspds/MODISCatalogRelation.scala
Speeds up `experimental/it:test` from 527s to 194s.
=> Applying pre-partitioning to DataSources.

core/src/main/scala/org/locationtech/rasterframes/util/DataFrameRenderers.scala, core/src/test/scala/org/locationtech/rasterframes/ExtensionMethodSpec.scala
=> Added forced truncation of WKT types in Markdown/HTML rendering.

.circleci/config.yml, build/circleci/Dockerfile, pyrasterframes/src/main/python/docs/sjoin.pymd, pyrasterframes/src/main/python/requirements.txt
Enables use of geopandas spatial join in the docs and other parts of the build process, and for downstream apps.
=> Add libspatialindex and rtree to test environment

core/src/main/scala/org/locationtech/rasterframes/model/LazyCRS.scala, core/src/test/scala/org/locationtech/rasterframes/model/LazyCRSSpec.scala
Related to #438 
Adds  some additional keywords that are supported under the geotrellis.proj4.io.wkt parsing module. 
The implementations under the hood here are quite strict to the exact expression of the WKT string, for instance it seems the `name`s have to be exactly equal, though in practice the names seem to vary by different sources giving otherwise equivalent CRS. 
In general the user would be best served to use an EPSG code if known, or proj string if that's appropriate.
=> Refine CRS WKT parsing error message and test

.circleci/config.yml, pyrasterframes/src/main/python/requirements.txt
Fix for:
```
#!/bin/bash -eo pipefail
pip3 install --quiet --user -r pyrasterframes/src/main/python/requirements.txt
ERROR: Invalid requirement: 'ipython=6.2.1' (from line 1 of pyrasterframes/src/main/python/requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```
=> Fix for docs build failure on incorrect requirements.txt

rf-notebook/src/main/docker/requirements-nb.txt
Contains fixes for issues that were contaminating the `PATH` environment variable and causing the `spark-submit` to fail.
=> Upgrade rasterframes-notebook container version of rtree.

core/src/main/scala/org/locationtech/rasterframes/functions/TileFunctions.scala, core/src/test/scala/org/locationtech/rasterframes/functions/TileFunctionsSpec.scala
rf_tile_to_array_int returns an array of Int.
Signed-off-by: Jean-Denis Giguère <jean-denis@anagraph.io>
=> rf_tile_to_array_int returns Int, not double. Fix #473

project/PythonBuildPlugin.scala, pyrasterframes/build.sbt, pyrasterframes/src/main/python/setup.py
Partial addressing of #459. pyrasterframes version numbers should be in sync with sbt, and PEP 440 compliant. At least for the cases we normally encounter.
=> Synchronize PEP 440 version with Maven/SBT

.circleci/config.yml, core/src/test/scala/org/locationtech/rasterframes/ref/RasterSourceSpec.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/geotiff/package.scala, datasource/src/test/scala/examples/ExplodeWithLocation.scala, datasource/src/test/scala/examples/ValueAtPoint.scala
Also: Refined extension methods on GeoTiffRasterFrameWriter.
=> Added a couple example inspired by Gitter discussion

core/src/test/scala/org/locationtech/rasterframes/TestEnvironment.scala, pyrasterframes/src/main/python/tests/__init__.py
This should reduce spurious failures on CI builds
=> Set spark master with spark.task.maxFailures in test

core/src/main/scala/org/locationtech/rasterframes/expressions/transformers/ReprojectGeometry.scala, core/src/test/scala/org/locationtech/rasterframes/ReprojectGeometrySpec.scala
Author: Netanel Malka <netanel246@gmail.com>
st_reproject throws on encountering null value in the column - #501
Added null check on ReprojectGeometry
Added test for that
Signed-off-by: Netanel Malka <netanel246@gmail.com>
=> Fix st_reproject throws on encountering null value in column

core/src/main/scala/org/locationtech/rasterframes/encoders/StandardEncoders.scala, core/src/main/scala/org/locationtech/rasterframes/encoders/TypedEncoders.scala, core/src/main/scala/org/locationtech/rasterframes/ref/RFRasterSource.scala, core/src/main/scala/org/locationtech/rasterframes/tiles/ProjectedRasterTile.scala, core/src/test/scala/org/locationtech/rasterframes/expressions/SFCIndexerSpec.scala, docs/src/main/paradox/release-notes.md, pyrasterframes/src/main/python/setup.py, rf-notebook/src/main/docker/requirements-nb.txt
Without this fix workers may try to access Encoders before registering UDTs.
Tested both 66cca65 and 8b5c165 within the k8s notebook.
The image to play with is ` quay.io/daunnc/rasterframes-notebook:0.10.1-SNAPSHOT`
=> Fix UDTs registration ordering

build.sbt, core/src/main/scala/org/locationtech/rasterframes/expressions/aggregates/ProjectedLayerMetadataAggregate.scala, datasource/src/main/resources/META-INF/services/org.apache.spark.sql.sources.DataSourceRegister, datasource/src/main/resources/slippy.html, datasource/src/main/scala/org/locationtech/rasterframes/datasource/package.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/slippy/DataFrameSlippyExport.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/slippy/RenderingModes.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/slippy/RenderingProfiles.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/slippy/SlippyDataSource.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/slippy/package.scala, datasource/src/main/scala/org/locationtech/rasterframes/datasource/tiles/TilesDataSource.scala, datasource/src/test/scala/org/locationtech/rasterframes/datasource/slippy/SlippyDataSourceSpec.scala
Requires #571 
Adds ability to write out a RasterFrame as a slippy map for visualization. Provides color compositing and rendering options for tweaking results.
=> Slippy map writing support.
